name: Test after push
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
jobs:
  Run-front-e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v4
      - name: setup Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: '23.0'
          cache: npm
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: run e2e
        run: npm run test:e2e
